/**
 * Curated topic backlog for the autonomous scheduler: widely prescribed
 * medications patients most often have questions about. The scheduler walks
 * this list, skipping medications that already have a brief or published
 * video for the channel.
 *
 * Sources for inclusion: commonly dispensed U.S. prescriptions (the exact
 * ranking is not asserted anywhere in video content — content facts always
 * come from the per-medication FDA/NIH evidence bundle at production time).
 */
export const MEDICATION_BACKLOG: readonly string[] = [
  'atorvastatin',
  'metformin',
  'lisinopril',
  'levothyroxine',
  'amlodipine',
  'metoprolol',
  'albuterol',
  'omeprazole',
  'losartan',
  'gabapentin',
  'hydrochlorothiazide',
  'sertraline',
  'simvastatin',
  'montelukast',
  'escitalopram',
  'rosuvastatin',
  'bupropion',
  'furosemide',
  'pantoprazole',
  'trazodone',
  'fluoxetine',
  'duloxetine',
  'prednisone',
  'amoxicillin',
  'citalopram',
  'apixaban',
  'warfarin',
  'clopidogrel',
  'aspirin',
  'insulin glargine',
  'tamsulosin',
  'carvedilol',
  'venlafaxine',
  'alprazolam',
  'ibuprofen',
  'acetaminophen',
  'cyclobenzaprine',
  'methylphenidate',
  'amphetamine',
  'oxycodone',
  'tramadol',
  'clonazepam',
  'zolpidem',
  'meloxicam',
  'naproxen',
  'spironolactone',
  'glipizide',
  'semaglutide',
  'empagliflozin',
  'sitagliptin',
  'ezetimibe',
  'fenofibrate',
  'allopurinol',
  'famotidine',
  'ondansetron',
  'loratadine',
  'cetirizine',
  'fluticasone',
  'budesonide',
  'doxycycline',
  'azithromycin',
  'cephalexin',
  'ciprofloxacin',
  'nitrofurantoin',
  'valacyclovir',
  'sildenafil',
  'finasteride',
  'estradiol',
  'norethindrone',
  'lamotrigine',
  'levetiracetam',
  'topiramate',
  'quetiapine',
  'aripiprazole',
  'risperidone',
  'lithium',
  'buspirone',
  'hydroxyzine',
  'propranolol',
  'clonidine',
] as const;
